-- MySQL Script generated by MySQL Workbench
-- Thu Aug 22 14:46:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lexi_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lexi_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lexi_db` DEFAULT CHARACTER SET utf8 ;
USE `lexi_db` ;

-- -----------------------------------------------------
-- Table `lexi_db`.`words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lexi_db`.`words` ;

CREATE TABLE IF NOT EXISTS `lexi_db`.`words` (
  `id_word` INT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(45) NOT NULL,
  `times_used` INT NOT NULL DEFAULT 1,
  `update_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_word`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lexi_db`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lexi_db`.`notifications` ;

CREATE TABLE IF NOT EXISTS `lexi_db`.`notifications` (
  `id_notification` INT NOT NULL AUTO_INCREMENT,
  `notification_text` VARCHAR(2000) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_notification`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
